[workspace]
members = [
  'thread',
  'channel',
  "mutex",
  'operator',
  'macro_rules',
  'MyStack',
  'rs_test',
  'course',
  'rwlock',
  'condvar',
  'semaphore',
  'atomic',
  'send',
  'sync',
]
